letsencrypt/acme-spec

draft-barnes-acme.md
This PR closes #23.  It updates the overall flow of the protocol to make better use of HTTP.  There are no changes to the validation challenges.  In case it helps, there's a side-by-side comparison of protocol messages here:
http://www.ipv.sx/tmp/restification.html
=> RESTification

draft-barnes-acme.md
The [CABF Baseline Requirements (Section 10.3.1)](https://cabforum.org/wp-content/uploads/BRv1.2.3.pdf) require CAs to obtain agreement with a "Subscriber Agreement" or "Terms of Use" before they will issue a certificate.  We can reflect this requirement in ACME with a new challenge type that allows an applicant for authorization to agree to terms for the issuance of certs under that authorization.
=> Add an "agreement" challenge

draft-barnes-acme.md
This fixes broken HTML output encountered in #80.
=> Fix too short closing marker

draft-barnes-acme.md
There is no practical reason to allow this; also, it's a confusing use of the
word "nonce" (nonces aren't supposed to be reused by definition).
Discussed with @jsha in person today.
=> Don't allow server to reuse "nonce" in DVSNI

.gitignore, README.md
It's a bit unwise to recommend `sudo pip`, please use virtualenv instead.
=> Use virtualenv for i-d-template

draft-barnes-acme.md
I'm guessing that IPv6 records are ignored by the Simple HTTPS and DVSNI challenge methods? The current text seems to assume "the host for the domain" is uniquely defined, which puts an incorrect security model in the reader's head.
I think it's wise to explicitly exclude validation over IPv6 for now, because an attacker who controls the DNS zone could add an AAAA record to it without breaking the live site for most users, and if letsencrypt would send the challenge to that AAAA address, it would not be testing the "real" live site in practice.
=> Mention IPv6 and round-robin DNS situation

draft-barnes-acme.md
Minimal changes necessary to synchronize the examples/description to use an array for challenges.
(Background: The original restify branch used a dictionary for the challenges within the authorization resource.  However, the decision was made to use arrays as a dictionary does not allow for multiple challenges to be issued of the same type.  Combinations also uses indices which makes more sense if using an array.)
=> Fix auth resource challenge description/examples

draft-barnes-acme.md
The new version posts the certificate to be revoked and doesn't require knowledge of the certificate's resource URL. The goal is that if someone is only in possession of a certificate's private key, they should be able to revoke that certificate, even if they don't have the issuance history or other data.
This change also removes the "time to revoke" parameter. For now, all client-requested revocations will take place immediately.
Blocks https://github.com/letsencrypt/boulder/pull/147 (revocation in WFE).
=>  Update revocation spec.

draft-barnes-acme.md
There should be one recovery token per account, not per identifier authorization resource.
cc: @jdkasten
=> Recovery tokens bound to Registration, not Authorization

draft-barnes-acme.md
Every since "recoveryToken" moved to the registration object, it has logically applied to registrations, not authorizations.  But there remained scattered references to it throughout the text.  This PR is an attempt to clean that up.
Note: This PR also removes the "recoveryContact" challenge type, because that doesn't make sense at the authorization / challenge level either.  We should re-add this at the registration level.  I have filed a #136 to track this.
=> Refactor recovery to apply to registrations

draft-barnes-acme.md
The existing messages have URIs present where they're not helpful, and missing where they would be helpful.  This PR makes two changes:
* Removes the "authorizations" URIs from the new-certificate request object
* Adds "certificates" and "authorizations" URIs to the registration object
=> Shift URIs around

draft-barnes-acme.md
After the last change it accidentally said validation requests are vulnerable to
the off-path attacker, when it should have said they are vulnerable to the
on-path attacker.
=> Fix error in threat model description.

draft-barnes-acme.md
This updates the list of error codes in the ACME protocol to reflect new codes that have recently been added to Boulder. These new errors can occur when DV fails. They should be used to give the client additional information which can programmatically help the user identify and fix the problem.
=> Updated error codes

draft-barnes-acme.md
The ACME draft suggests that after a client has lost "all keys and recovery tokens", the CA should ask him to get a "recertification by another CA".
That would have no point: there would be no reason for a Certificate Authority to consider that a "Recertification by another CA" is more trustworthy than their "recertifying" the client themselves [1].
That statement seems to assume that "another CA" would perform a check of client's legal identity (as is currently done when issuing EV certificates). It may have been written with point of view of the "Let's encrypt" project which isn't going to be performing such checks (and would therefore rely on other CAs to perform them).
This patch clarifies the meaning.
---
[1] "After You were so silly to lose all Your keys and Your recovery token, we …
=> Identifier Validation Challenges: clarify "Recertification by another CA"

draft-barnes-acme.md
In order to allow ACME to be run over a CDN or other architecture with off-loaded TLS termination, it is important that the protocol be resilient in the face of a TLS MitM.
The basic risk we need to defend against is the MitM being able to hijack a legitimate authorization transaction to authorize its own keys.  If only the right keys are authorized, then client signing assures that certificate requests and revocation requests are OK. (Modulo URL switching attacks, which I don't think are an issue in the current protocol.)  Keys get authorized via validation and recovery, so this PR does the following:
* Use JWS in simpleHttp to bind the challenge to the account key pair (DVSNI already has this property)
* Use MitM-resistent recovery mechanisms
Closes #14
Closes #115 
Closes #157
=> Improve MitM resistance

draft-barnes-acme.md
Certificate renewal should be client-initiated, and should follow the pattern we established with revoke-cert.  (Though we should refer to the certificate by reference, rather than by value.)
This is currently WIP, pending rebase on #138.
Closes #58
Closes #59 
Closes #125
=> Add a renew-cert endpoint

draft-barnes-acme.md
Fixes #173 
Changes:
* Remove "alg" because there are no unacceptable JWS algorithms
* Remove "token" because it interferes with ability to compute offline
* Make "jwk" array since there can be multiple public keys
* Remove "authorizedFor" because it leaks information and doesn't really add anything
* Remove "certFingerprints", "subjectKeyIdentifiers", "serialNumbers"
* Server has to have cert to form challenge
* ... so it might as well just send the cert.
* Change signed value to be a JWS that:
1. Includes the account key and identifiers being authorized
2. Can be computed off-line
* Revise validation procedure to match the above
=> Refactor Proof-of-Possession challenge

draft-barnes-acme.md
Fix #183  After much discussion with @bifurcation and @pde.
Compute Z, where Z is the SHA-256 of the JWS signature value.  Z is encoded in hexidecimal form.
Place Z in a subjectAltName of the form <Z[0:32]>.<Z[32:64]>.acme.invalid
=> Avoid 64 character limit in organizationName

draft-barnes-acme.md
Copies the language from the DNS challenge to the other challenges (characters must be in Base64 URL-safe set). This is particularly helpful for SimpleHTTP since it prohibits '/' and '.' in tokens, which wind up used in path names.
Fixes some tokens with characters outside the URL-safe base64 set, and fixes one
token that was randomly different from the other example tokens.
Fixes trailing commas in JSON.
=> Clarify tokens in various challenges.

draft-barnes-acme.md
This PR fixes a typo in the Identifier Validation Challenges section.
=> Fix minor typo in draft-barnes-acme.md

README.md
Make note in README clear that this repo is not guaranteed to be
up to date with the latest version of the ACME protocol.
Closes letsencrypt/acme-spec#231
=> Clarify warning in README
