letsencrypt/acme-spec

draft-barnes-acme.md

FQDN identifier: domain -> dns

---

draft-barnes-acme.md

Corrected a number of minor mistakes.

Fix minor spelling and grammar errors

---

draft-barnes-acme.txt
index.html

Generated with `make gh-pages`. Temporarily fixes #76, but please consider fixing #78 for the long term. You can view it at http://kuba.github.io/acme-spec/

Update GitHub Pages

---

draft-barnes-acme.md

Based on Boulder source code at letsencrypt/boulder@8dc00128b6cee0c2ee082876444cfdba77c752b4.

Update possible values for "status" field.

---

draft-barnes-acme.md

Server MUST set "next" link for Registration Resource

---

draft-barnes-acme.md

c.f. https://github.com/letsencrypt/boulder/issues/128, https://github.com/letsencrypt/boulder/issues/170

Do not require "instance" on problem document

---

draft-barnes-acme.md

This PR fixes the bad rendering in -01, and cleans up some minor reference issues.  No substantive changes.

Fix RFC rendering

---

draft-barnes-acme.md

Also clarify language around keys vs accounts in a few places.
Fixes https://github.com/letsencrypt/acme-spec/issues/92
Fixes https://github.com/letsencrypt/acme-spec/issues/127
Fixes https://github.com/letsencrypt/acme-spec/issues/98

Remove 'key' and 'contact' from authorization objects.

---

draft-barnes-acme.md

Fixes #108.
Fixes #124.
cc @bifurcation @pde for code review.

Replace SimpleHTTPS with SimpleHTTP.

---

draft-barnes-acme.md

This is a first pass at the replay protection we discussed on the mailing list.
Fixes https://github.com/letsencrypt/acme-spec/issues/122
Related to https://github.com/letsencrypt/boulder/issues/165

Add replay protection and a threat model.

---

draft-barnes-acme.md

Add an anti-replay nonce facility

---

draft-barnes-acme.md

- @martinthomson comments
- https://github.com/letsencrypt/acme-spec/pull/140/files#r31936785
- https://github.com/letsencrypt/acme-spec/pull/140/files#r31937211
- "One" -> "Once"

Fix typos.

---

draft-barnes-acme.md

Recommend sending permissive CORS headers

---

.travis.yml
Makefile
lib/style.css

Ran `make update; travis encrypt -a -p GH_TOKEN=<my secret>`

Adding travis keys; updating makefile

---

draft-barnes-acme.md

Some trailing spaces, bullet list construction.

Fixing formatting

---

draft-barnes-acme.md

This PR rolls up a bunch of minor clarifications and fixes requested in issues.
Fixes #13, #60, #64, #89, #90, #93, #154, and #159.

Miscellaneous fixes and clarifications

---

draft-barnes-acme.md

This allows clients to be configured with a single URL that will give them information about the other URLs available for various resources.

Add directory object

---

draft-barnes-acme.md

Note that you get a fresh nonce with HEAD

---

draft-barnes-acme.md

Fixes #165 
Fixes #163 
Fixes #131 
Fixes #39

Add security considerations

---

draft-barnes-acme.md

Wrap to 80 cols and remove blank lines in figures

---

draft-barnes-acme.md

* Pulled out a "protocol elements" section separate from the "Cert Management" section
* Removed "Other Possibilities" under challenges section
* Light editing pass; tweaked a few SHOULDs / MUSTs
* Re-flowed some areas
* Spell check
Fixes #147 
Fixes #110

Miscellaneous editorial changes

---

draft-barnes-acme.md

Remove a last vestige of ECDH in the DNS challenge.  Minor change, merging without review.

Derived key -> account key

---

draft-barnes-acme.md

This builds off of #179 and the previous discussion in #175.  It is also created as a separate branch within this repo to make it easier to edit.

Simplify DVSNI

---

draft-barnes-acme.md

Editorial suggestions in regards to spelling and word repetition.

Spelling & word repetition fixes.

---

draft-barnes-acme.md

Thanks to @jsha and @jdkasten for some review comments after the IETF draft was submitted.  This PR fixes those issues.
Fixes #178 
Fixes #187 
Fixes #188 
Fixes #191 
Fixes #192 
Fixes #193

Fixes to post-IETF-submission issues

---

draft-barnes-acme.md

This supercedes #206... addressing @jsha's comments.

Simplehttp v04 cleanup

---

draft-barnes-acme.md

While working on the client implementation of Simple HTTP challenge I discovered multiple inconsistencies in the description and examples. 
@jdkasten PTAL
cc: @jmhodges

Cleanup Simple HTTP challenge description and examples.
